### PR TITLE
Improved pagination.

### PR DESCRIPTION
**Pull request by jaquer**
Link for 'older/newer updates' pages only show if there's more pages to be shown in their corresponding directions.

### CODE REVIEW

**Review by oelna — COMMENTED** [review]
I like the idea, but from a UI point of view, my philosophy has been to rather show disabled options than show/hide them. I think it promotes the development of muscle memory for UI elements. My main inspiration for this were the common Mac/Win menu bar menus and items.

Since there is a `disabled` class already, the non-functional link can be grayed out or completely hidden via CSS pretty easily.

What is your main motivation behind this change? A case could be made to add a `rel="nofollow"` to the disabled links.

**Comment by jaquer** [comment]
Hi @oelna! Thank you for the app, and for considering the PR.

Personally, I didn't like the fact that the "older updates" link would be enabled taking you to 'microblog/page/2' only to be shown there's no more posts, and *that* page has an "older updates" link that takes you to 'microblog/page/3' with no posts, and so on.

If you prefer I can change it so the links are hidden instead.

**Comment by oelna** [comment]
After looking at it for a bit more, I have changed my mind on this. Thank you very much for your input.

**Comment by jaquer** [comment]
My pleasure. Happy to contribute. I have a couple more to cleanup and submit.

**Pull request merged**
